from django.urls import path
from apps.femi_api.views import (
    ProcessTransactionAPIView,
    DashboardKPIAPIView,
    BatchTransactionAPIView,
    ExportTransactionAPIView,
    HealthCheckAPIView,
    LoginAPIView,
    RegisterAPIView,
    KpiNiveauAPIView,
    LogoutAPIView,
    DeactivateAccountAPIView,
    LinkWhatsAppRequestAPIView,
    LinkWhatsAppConfirmAPIView,
    RegistreJournalierAPIView,
    EtatFinancierAPIView,
    GrandLivreAPIView,
    BilanSyntheseAPIView,
    BalanceGeneraleAPIView,
    BalanceAuxiliaireAPIView,
    ConfigAPIView,
)

urlpatterns = [
    path('transactions/process/', ProcessTransactionAPIView.as_view(), name='api_process_transaction'),
    path('transactions/batch/', BatchTransactionAPIView.as_view(), name='api_transaction_batch'),
    path('transactions/export/', ExportTransactionAPIView.as_view(), name='api_transaction_export'),
    path('dashboard/kpis/', DashboardKPIAPIView.as_view(), name='api_dashboard_kpis'),
    path('registre-journalier/', RegistreJournalierAPIView.as_view(), name='api_registre_journalier'),
    path('etat-financier/', EtatFinancierAPIView.as_view(), name='api_etat_financier'),
    path('grand-livre/', GrandLivreAPIView.as_view(), name='api_grand_livre'),
    path('balance-generale/', BalanceGeneraleAPIView.as_view(), name='api_balance_generale'),
    path('balance-auxiliaire/', BalanceAuxiliaireAPIView.as_view(), name='api_balance_auxiliaire'),
    path('bilan/synthese/', BilanSyntheseAPIView.as_view(), name='api_bilan_synthese'),
    path('config/', ConfigAPIView.as_view(), name='api_config'),
    path('health/', HealthCheckAPIView.as_view(), name='api_health'),
    path('auth/token/', LoginAPIView.as_view(), name='api_auth_token'),
    path('auth/register/', RegisterAPIView.as_view(), name='api_auth_register'),
    path('auth/logout/', LogoutAPIView.as_view(), name='api_auth_logout'),
    path('kpi/<int:numero>/', KpiNiveauAPIView.as_view(), name='api_kpi_niveau'),
    path('auth/deactivate/', DeactivateAccountAPIView.as_view(), name='api_auth_deactivate'),
    path('auth/link-whatsapp/request/', LinkWhatsAppRequestAPIView.as_view(), name='api_link_whatsapp_request'),
    path('auth/link-whatsapp/confirm/', LinkWhatsAppConfirmAPIView.as_view(), name='api_link_whatsapp_confirm'),
]