# Generated by Django 5.2.17 on 2026-09-08 22:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("rccm", models.CharField(blank=True, max_length=100, null=True)),
                ("ifu", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "regime_fiscal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("devise", models.CharField(default="XOF", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
            },
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField(unique=True)),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "est_a_partir_de",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si le prix est un prix de départ ('À partir de')",
                    ),
                ),
                ("devise", models.CharField(default="EUR", max_length=5)),
                ("duree_jours", models.PositiveIntegerField(default=30)),
                (
                    "populaire",
                    models.BooleanField(
                        default=False, help_text="Badge 'Le plus choisi'"
                    ),
                ),
                (
                    "fonctionnalites",
                    models.JSONField(
                        default=list, help_text="Liste des fonctionnalités incluses"
                    ),
                ),
                (
                    "limite_operations_mensuelles",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "limite_utilisateurs",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Secteur d'activité",
                "verbose_name_plural": "Secteurs d'activité",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("FOURNISSEUR", "Fournisseur")],
                        max_length=15,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "telephone_whatsapp",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilisateurs",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="InsightIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANOMALIE", "Anomalie"),
                            ("TENDANCE", "Tendance"),
                            ("PREVISION", "Prévision"),
                            ("ALERTE", "Alerte"),
                            ("RECOMMANDATION", "Recommandation"),
                            ("OPPORTUNITE", "Opportunité"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("action_recommandee", models.TextField(blank=True, null=True)),
                (
                    "niveau_gravite",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("ATTENTION", "Attention"),
                            ("CRITIQUE", "Critique"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("date_detection", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight IA",
                "verbose_name_plural": "Insights IA",
                "ordering": ["-date_detection"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("RECETTE", "Recette"), ("DEPENSE", "Dépense")],
                        max_length=10,
                    ),
                ),
                ("amount_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=10)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("transaction_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "vendor_or_client",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération",
                "verbose_name_plural": "Opérations",
            },
        ),
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prix_paye", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("EXPIRE", "Expiré"),
                            ("ANNULE", "Annulé"),
                            ("EN_ATTENTE", "En attente"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to="femi_account.entreprise",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abonnements",
                        to="femi_account.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Kpi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("icone", models.CharField(blank=True, max_length=10, null=True)),
                ("formule_description", models.TextField(blank=True, null=True)),
                ("unite", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="femi_account.niveau",
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide si le KPI est commun à tous les secteurs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="femi_account.secteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
            },
        ),
        migrations.AddField(
            model_name="entreprise",
            name="secteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entreprises",
                to="femi_account.secteur",
            ),
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("RECETTE", "Recette"), ("DEPENSE", "Dépense")],
                        max_length=10,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "unique_together": {("entreprise", "nom", "type")},
            },
        ),
    ]
