# Generated by Django 5.2.17 on 2026-08-28 14:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "rccm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="N° RCCM"
                    ),
                ),
                (
                    "ifu",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="N° IFU / NIF",
                    ),
                ),
                (
                    "regime_fiscal",
                    models.CharField(
                        choices=[
                            ("TPS", "Taxe Professionnelle Synthétique"),
                            ("REEL_SIMPLIFIE", "Régime Réel Simplifié"),
                            ("REEL_NORMAL", "Régime Réel Normal"),
                        ],
                        default="TPS",
                        max_length=50,
                    ),
                ),
                ("adresse", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("devise", models.CharField(default="XOF", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur Système"),
                            ("DIRIGEANT", "Dirigeant / Promoteur"),
                            ("COMPTABLE", "Comptable / Expert-Comptable"),
                            ("EMPLOYE", "Employé / Saisie"),
                        ],
                        default="DIRIGEANT",
                        max_length=20,
                    ),
                ),
                (
                    "telephone_whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Numéro au format international (ex: +22890000000) pour l'identification WhatsApp",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utilisateurs",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECETTE", "Recette (Vente / Encaissement)"),
                            ("DEPENSE", "Dépense (Achat / Décaissement)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount_ht",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("amount_ttc", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=5)),
                ("category", models.CharField(max_length=100)),
                (
                    "vendor_or_client",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("BANK_TRANSFER", "Virement Bancaire"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CARD", "Carte Bancaire"),
                            ("UNKNOWN", "Inconnu"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                ("confidence_score", models.FloatField(default=1.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WHATSAPP", "WhatsApp"),
                            ("MOBILE", "Application Mobile"),
                            ("API", "API Externe"),
                        ],
                        default="API",
                        max_length=10,
                    ),
                ),
                ("raw_input_text", models.TextField(blank=True, null=True)),
                (
                    "receipt_image",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operations_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération Comptable",
                "verbose_name_plural": "Opérations Comptables",
                "ordering": ["-created_at"],
            },
        ),
    ]
