# Generated by Django 6.1.1 on 2026-09-08 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=5)),
                ('duree_jours', models.PositiveIntegerField(default=30)),
                ('limite_operations_mensuelles', models.PositiveIntegerField(blank=True, null=True)),
                ('limite_utilisateurs', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Secteur d'activité",
                'verbose_name_plural': "Secteurs d'activité",
            },
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Opération', 'verbose_name_plural': 'Opérations'},
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='amount_ht',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='raw_input_text',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='devise',
            field=models.CharField(default='XOF', max_length=10),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ifu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='rccm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='regime_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='currency',
            field=models.CharField(default='XOF', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='transaction_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='transaction_type',
            field=models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone_whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur')], max_length=15)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='femi_account.entreprise')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='InsightIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ANOMALIE', 'Anomalie'), ('TENDANCE', 'Tendance'), ('PREVISION', 'Prévision'), ('ALERTE', 'Alerte'), ('RECOMMANDATION', 'Recommandation'), ('OPPORTUNITE', 'Opportunité')], max_length=20)),
                ('message', models.TextField()),
                ('action_recommandee', models.TextField(blank=True, null=True)),
                ('niveau_gravite', models.CharField(choices=[('INFO', 'Information'), ('ATTENTION', 'Attention'), ('CRITIQUE', 'Critique')], default='INFO', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='femi_account.entreprise')),
            ],
            options={
                'verbose_name': 'Insight IA',
                'verbose_name_plural': 'Insights IA',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='femi_account.entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='femi_account.plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('icone', models.CharField(blank=True, max_length=10, null=True)),
                ('formule_description', models.TextField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='femi_account.niveau')),
                ('secteur', models.ForeignKey(blank=True, help_text='Laisser vide si le KPI est commun à tous les secteurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='femi_account.secteur')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='femi_account.secteur'),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='femi_account.entreprise')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'unique_together': {('entreprise', 'nom', 'type')},
            },
        ),
    ]
