# Generated by Django 5.2.17 on 2026-09-09 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femi_account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceJustificative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom_fichier", models.CharField(max_length=255)),
                ("url_fichier", models.CharField(max_length=500)),
                ("type_mime", models.CharField(max_length=100)),
                ("taille_octets", models.PositiveIntegerField(blank=True, null=True)),
                ("date_televersement", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_justificatives",
                        to="femi_account.operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce justificative",
                "verbose_name_plural": "Pièces justificatives",
            },
        ),
    ]
