# Generated by Django 6.1.1 on 2026-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0002_niveau_plan_secteur_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='est_a_partir_de',
            field=models.BooleanField(default=False, help_text="Cocher si le prix est un prix de départ ('À partir de')"),
        ),
        migrations.AddField(
            model_name='plan',
            name='fonctionnalites',
            field=models.JSONField(default=list, help_text='Liste des fonctionnalités incluses'),
        ),
        migrations.AddField(
            model_name='plan',
            name='populaire',
            field=models.BooleanField(default=False, help_text="Badge 'Le plus choisi'"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='devise',
            field=models.CharField(default='EUR', max_length=5),
        ),
    ]
