# Generated by Django 5.2.17 on 2026-09-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femi_account", "0002_piecejustificative"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations",
                to="femi_account.contact",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="montant_paye",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cumul des paiements reçus. Pour une opération PAYE, correspond au montant total (voir save()).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="statut_paiement",
            field=models.CharField(
                choices=[("PAYE", "Payé"), ("CREDIT", "À crédit")],
                default="PAYE",
                max_length=10,
            ),
        ),
    ]
