# Generated by Django 5.2.17 on 2026-09-09 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femi_account", "0003_operation_contact_operation_montant_paye_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("RECETTE", "Recette"),
                    ("DEPENSE", "Dépense"),
                    ("PRET_DONNE", "Prêt donné"),
                    ("PRET_RECU", "Prêt reçu"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cout_unitaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "duree_estimee_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations",
                        to="femi_account.entreprise",
                    ),
                ),
            ],
            options={
                "unique_together": {("entreprise", "nom")},
            },
        ),
        migrations.CreateModel(
            name="PrestationRealisee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "prix_unitaire_facture",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("duree_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "sous_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_realisees",
                        to="femi_account.operation",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="realisations",
                        to="femi_account.prestation",
                    ),
                ),
            ],
        ),
    ]
