# Generated by Django 5.2.17 on 2026-09-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femi_account", "0004_alter_operation_transaction_type_prestation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
