# Generated by Django 5.2.17 on 2026-09-10 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femi_account", "0005_alter_utilisateur_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppLinkRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telephone_whatsapp", models.CharField(max_length=30)),
                ("code", models.CharField(max_length=6)),
                ("tentatives", models.PositiveSmallIntegerField(default=0)),
                ("utilisee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_link_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de liaison WhatsApp",
                "verbose_name_plural": "Demandes de liaison WhatsApp",
            },
        ),
    ]
