# Generated by Django 5.2.17 on 2026-09-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0006_whatsapplinkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='type_activite',
            field=models.CharField(blank=True, help_text='ex: achatvent, depotvente, personnel', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='type_entreprise',
            field=models.CharField(blank=True, help_text='ex: individuel, sarl, sa, autre', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
