# Generated by Django 5.2.17 on 2026-09-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0007_abonnement_mode_paiement_entreprise_type_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
