# Generated by Django 5.2.17 on 2026-09-17 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0008_entreprise_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal_origine', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('MOBILE', 'Application Mobile')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='femi_account.entreprise')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('MOBILE', 'Application Mobile')], max_length=10)),
                ('expediteur', models.CharField(choices=[('USER', 'Utilisateur'), ('AGENT', 'Agent Femi')], max_length=10)),
                ('type_message', models.CharField(choices=[('TEXTE', 'Texte'), ('AUDIO', 'Audio'), ('IMAGE', 'Image')], default='TEXTE', max_length=10)),
                ('contenu_texte', models.TextField(blank=True, null=True)),
                ('fichier_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='femi_account.conversation')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_lies', to='femi_account.operation')),
            ],
            options={
                'verbose_name': 'Message de conversation',
                'verbose_name_plural': 'Historique des conversations',
                'ordering': ['created_at'],
            },
        ),
    ]
