# Generated by Django 5.2.17 on 2026-09-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0009_conversation_conversationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheanceFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echeance', models.CharField(choices=[('TVA', 'Déclaration TVA (Mensuel)'), ('TPU_ACOMPTE', 'Acompte TPU / Patente (Trimestriel)'), ('LIASSE_ANNUELLE', 'Bilan Annuel / Liasse SYSCOHADA'), ('DAS', 'Déclaration Annuelle des Salaires'), ('AUTRE', 'Autre obligation OTR')], max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RAPPELE', 'Rappel envoyé'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('dernier_rappel_envoye', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_fiscales', to='femi_account.entreprise')),
            ],
            options={
                'verbose_name': 'Échéance Fiscale',
                'verbose_name_plural': 'Échéances Fiscales',
                'ordering': ['date_echeance'],
            },
        ),
    ]
