# Generated by Django 5.2.17 on 2026-09-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0009_abonnement_transaction_id_abonnement_payment_url'),
        ('femi_account', '0010_echeancefiscale'),
    ]

    operations = [
    ]
