# Generated by Django 5.2.17 on 2026-09-20 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0011_merge_20260920_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Cat??gorie', 'verbose_name_plural': 'Cat??gories'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Op??ration', 'verbose_name_plural': 'Op??rations'},
        ),
        migrations.AlterModelOptions(
            name='piecejustificative',
            options={'verbose_name': 'Pi??ce justificative', 'verbose_name_plural': 'Pi??ces justificatives'},
        ),
        migrations.AlterModelOptions(
            name='secteur',
            options={'verbose_name': "Secteur d'activit??", 'verbose_name_plural': "Secteurs d'activit??"},
        ),
        migrations.AddField(
            model_name='echeancefiscale',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expir??'), ('ANNULE', 'Annul??'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'D??pense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='insightia',
            name='type',
            field=models.CharField(choices=[('ANOMALIE', 'Anomalie'), ('TENDANCE', 'Tendance'), ('PREVISION', 'Pr??vision'), ('ALERTE', 'Alerte'), ('RECOMMANDATION', 'Recommandation'), ('OPPORTUNITE', 'Opportunit??')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='secteur',
            field=models.ForeignKey(blank=True, help_text='Laisser vide si le KPI est commun ?? tous les secteurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='femi_account.secteur'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des paiements re??us. Pour une op??ration PAYE, correspond au montant total (voir save()).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='operation',
            name='statut_paiement',
            field=models.CharField(choices=[('PAYE', 'Pay??'), ('CREDIT', '?? cr??dit')], default='PAYE', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='transaction_type',
            field=models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'D??pense'), ('PRET_DONNE', 'Pr??t donn??'), ('PRET_RECU', 'Pr??t re??u')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='est_a_partir_de',
            field=models.BooleanField(default=False, help_text="Cocher si le prix est un prix de d??part ('?? partir de')"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fonctionnalites',
            field=models.JSONField(default=list, help_text='Liste des fonctionnalit??s incluses'),
        ),
    ]
