# Generated by Django 5.2.17 on 2026-09-21 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0012_alter_categorie_options_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppareilNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('plateforme', models.CharField(blank=True, choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil de notification',
                'verbose_name_plural': 'Appareils de notification',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('palier', models.CharField(blank=True, choices=[('J7', '7 jours avant'), ('J3', '3 jours avant'), ('J1', '1 jour avant'), ('J0', 'Jour J'), ('RETARD', 'Échéance dépassée')], max_length=10)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echeance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='femi_account.echeancefiscale')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'lue'], name='femi_accoun_utilisa_78ac6b_idx')],
                'unique_together': {('utilisateur', 'echeance', 'palier')},
            },
        ),
    ]
