# Generated by Django 5.2.17 on 2026-09-25 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0013_appareilnotification_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Opération', 'verbose_name_plural': 'Opérations'},
        ),
        migrations.AlterModelOptions(
            name='piecejustificative',
            options={'verbose_name': 'Pièce justificative', 'verbose_name_plural': 'Pièces justificatives'},
        ),
        migrations.AlterModelOptions(
            name='secteur',
            options={'verbose_name': "Secteur d'activité", 'verbose_name_plural': "Secteurs d'activité"},
        ),
        migrations.AddField(
            model_name='operation',
            name='amount_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='insightia',
            name='type',
            field=models.CharField(choices=[('ANOMALIE', 'Anomalie'), ('TENDANCE', 'Tendance'), ('PREVISION', 'Prévision'), ('ALERTE', 'Alerte'), ('RECOMMANDATION', 'Recommandation'), ('OPPORTUNITE', 'Opportunité')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='secteur',
            field=models.ForeignKey(blank=True, help_text='Laisser vide si le KPI est commun à tous les secteurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='femi_account.secteur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='palier',
            field=models.CharField(blank=True, choices=[('J10', '10 jours avant'), ('J5', '5 jours avant'), ('J1', '1 jour avant'), ('J0', 'Jour J'), ('RETARD', 'Échéance dépassée')], max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumul des paiements reçus. Pour une opération PAYE, correspond au montant total (voir save()).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='operation',
            name='statut_paiement',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('CREDIT', 'À crédit')], default='PAYE', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='transaction_type',
            field=models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense'), ('PRET_DONNE', 'Prêt donné'), ('PRET_RECU', 'Prêt reçu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='est_a_partir_de',
            field=models.BooleanField(default=False, help_text="Cocher si le prix est un prix de départ ('à partir de')"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fonctionnalites',
            field=models.JSONField(default=list, help_text='Liste des fonctionnalités incluses'),
        ),
    ]
