# Generated by Django 5.2.17 on 2026-09-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0014_alter_categorie_options_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancefiscale',
            name='montant_taxe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='echeancefiscale',
            name='operations',
            field=models.ManyToManyField(blank=True, related_name='echeances_fiscales', to='femi_account.operation'),
        ),
        migrations.AddField(
            model_name='echeancefiscale',
            name='periode',
            field=models.CharField(blank=True, help_text='Période fiscale au format YYYY-MM', max_length=7, null=True),
        ),
    ]
