# Generated by Django 5.2.17 on 2026-09-26 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0015_echeancefiscale_montant_taxe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 26, 23, 37, 43, 987705, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
