# Generated by Django 5.2.17 on 2026-09-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0016_operation_date_enregistrement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='date_enregistrement',
            new_name='created_at',
        ),
    ]
