# Generated by Django 5.2.17 on 2026-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0017_rename_date_enregistrement_operation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_action',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
