# Generated by Django 5.2.17 on 2026-09-30 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0017_rename_date_enregistrement_operation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pme_logos/')),
                ('telephone_pro', models.CharField(max_length=30)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('nif_rccm', models.CharField(blank=True, help_text='Identifiant Fiscal / RCCM pour la régularité fiscale', max_length=100, null=True)),
                ('moyens_paiement', models.TextField(blank=True, help_text='Ex: Mobile Money (TMoney / Flooz / Wave), RIB, etc.', null=True)),
                ('conditions_defaut', models.TextField(blank=True, default='Devis valable 30 jours.', help_text='Mentions légales de bas de page', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pme_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
