# Generated by Django 5.2.17 on 2026-10-05 00:07

import apps.femi_account.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0018_conversation_pending_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.femi_account.models.generer_reference_devis, editable=False, max_length=50, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('FACTURE', 'Transformé en Facture'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='femi_account.contact')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='femi_account.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description du produit ou service')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='femi_account.devis')),
            ],
        ),
    ]
