# Generated by Django 5.2.17 on 2026-10-09 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0018_conversation_pending_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text="Employé qui a enregistré l'opération (null pour les anciennes opérations).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
