# Generated by Django 5.2.17 on 2026-10-01 08:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0019_devis_lignedevis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='tva_taux',
            field=models.DecimalField(decimal_places=4, default=0.18, max_digits=5),
        ),
        migrations.AddField(
            model_name='pmeprofile',
            name='entreprise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pme_profile', to='femi_account.entreprise'),
        ),
        migrations.AddField(
            model_name='pmeprofile',
            name='tva_applicable',
            field=models.BooleanField(default=False, help_text="Indique si l'entreprise applique la TVA par défaut"),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_emission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero_devis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='total_ligne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
