# Generated by Django 5.2.17 on 2026-10-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0019_operation_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_activation_essais',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_activation_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_activation_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(blank=True, help_text="Intitulé affiché (ex. Serveuse). N'a aucun effet sur les droits, qui dépendent de role.", max_length=100, null=True),
        ),
    ]
