# Generated by Django 5.2.17 on 2026-10-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('femi_account', '0018_conversation_pending_action'),
        ('femi_account', '0020_devis_tva_taux_pmeprofile_entreprise_and_more'),
    ]

    operations = [
    ]
