"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-k*^^n_ssjekw7jiako25_k6+)4(h_-x(jkt$h(03qhkocg9b^f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # En-têtes CORS (Pour Flutter Web & clients externes)
    'corsheaders',
    
    # Framework d'API REST
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    
    # Vos 5 applications métiers Femi
    'apps.femi_agent',     # Moteur IA, LangChain, OCR, STT
    'apps.femi_account',   # Base de données comptable et modèles
    'apps.femi_api',       # API REST partagée
    'apps.femi_whatsapp',  # Integrations & Webhooks WhatsApp
]

MIDDLEWARE = [
    # CorsMiddleware doit impérativement précéder tout middleware renvoyant des réponses
    'corsheaders.middleware.CorsMiddleware',
    
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# --- CONFIGURATION CORS ---
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.ammhukotgebwmpibpycm',
        'PASSWORD': '(Femi-db)2026',  # Mot de passe Supabase
        'HOST': 'aws-1-eu-west-1.pooler.supabase.com',   # Host Supabase
        'PORT': '6543',
        'OPTIONS': {
            'sslmode': 'require',  # Requis pour la connexion sécurisée à Supabase
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

AUTH_USER_MODEL = 'femi_account.Utilisateur'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Femi Financial API',
    'DESCRIPTION': 'API REST pour l\'agent financier et comptable Femi (Mobile & WhatsApp)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

WHATSAPP_VERIFY_TOKEN = "femi_secret_token_2026"

FEMI_LLM_MODEL = config("FEMI_LLM_MODEL", default="mistral")
OLLAMA_BASE_URL = config("OLLAMA_BASE_URL", default="http://localhost:11434")

CSRF_TRUSTED_ORIGINS = [
    'https://epidermal-slum-shame.ngrok-free.dev',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

  